version: "3.9"
services:
  app:
    image: my-app
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_HOST: db
      FLASK_RUN_HOST: 0.0.0.0
    ports:
      - "5000:5000"
    restart: on-failure

  db:
    image: my-postgres
