apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: vampir/my-app:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_USER
          value: {{ .Values.db.user }}
        - name: DB_PASSWORD
          value: {{ .Values.db.password }}
        - name: DB_HOST
          value: "db"
        - name: FLASK_RUN_HOST
          value: "0.0.0.0"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000